spring:
  profiles: cloud
  application:
    name: api-gateway
    
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://${eureka.hostname}/actuator/info
    healthCheckUrl: https://${eureka.hostname}/actuator/health
    homePageUrl: https://${eureka.hostname}/
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.discovery-server-si.credentials.uri}
