spring:
  profiles: cloud
  application:
    name: visits-service
    
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.discovery-server-si.credentials.uri}
